"""create user activities table

Revision ID: 235b918324d4
Revises: 654c71f118f6
Create Date: 2025-03-26 21:21:06.732164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '235b918324d4'
down_revision: Union[str, None] = '654c71f118f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activities', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('user_activities', sa.Column('count', sa.Integer(), nullable=True))
    op.alter_column('user_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_user_activities_date'), 'user_activities', ['date'], unique=False)
    op.drop_column('user_activities', 'activity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activities', sa.Column('activity_type', postgresql.ENUM('LOGIN', 'TASK_COMPLETED', name='activitytype'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_activities_date'), table_name='user_activities')
    op.alter_column('user_activities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('user_activities', 'count')
    op.drop_column('user_activities', 'date')
    # ### end Alembic commands ###
