"""add user activities table

Revision ID: 654c71f118f6
Revises: 2b737026cce7
Create Date: 2025-03-25 15:38:12.157211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654c71f118f6'
down_revision: Union[str, None] = '2b737026cce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
